/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ACTIONS: typeof import('$src/store')['ACTIONS']
  const ENV: typeof import('$src/constants/ENV_VARS')['default']
  const STORES: typeof import('$src/store')['STORES']
  const a: typeof import('$src/app.svelte')['a']
  const app: typeof import('$src/app.svelte')['default']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const p: typeof import('$src/app.svelte')['p']
  const tooltip: typeof import('$src/ts/use')['tooltip']
  const tw: typeof import('tailwind-merge')['twMerge']
}
